name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Move to folder
      run: cd app
    - name: Unit tests
      run: .\gradlew test --stacktrace
